mysql -u root -p < schema.sql
mysql -u root -p < lhaplus.sql
mysql -u root -p < lhaplus_patch_9_22.sql
mysql -u root -p < lhaplus_patch_9_29.sql
mysql -u root -p < lhaplus_patch_10_13.sql
mysql -u root -p < lhaplus_patch_10_14.sql
mysql -u root -p < sugiyama_patch_11_11.sql
mysql -u root -p < lhaplus_patch_11_19.sql
mysql -u root -p < sugiyama_patch_11_25.sql
mysql -u root -p < lhaplus_patch_12_18.sql
mysql -u root -p < lhaplus_patch_12_26.sql
mysql -u root -p < lhaplus_patch_12_28.sql
mysql -u root -p < lhaplus_patch_1_18.sql
mysql -u root -p < lhaplus_patch_1_26.sql
mysql -u root -p < lhaplus_patch_1_30.sql
mysql -u root -p < lhaplus_patch_2_3.sql
mysql -u root -p < lhaplus_patch_2_22.sql
mysql -u root -p < lhaplus_patch_3_2.sql
mysql -u root -p < lhaplus_patch_3_17.sql
mysql -u root -p < user_pass.sql
